name: Zombies
version: '${project.version}'
main: me.arcademadness.omnomz.Main
api-version: 1.20
authors: [ Jake, Zombie ]
description: Zombies can HEAR YOU
commands:
  zombies:
    description: Gives information regarding the omnomz plugin.
    usage: /<command>
  zsummon:
    description: summons zombies around you
    usage: /<command>
    aliases: zs
  zsniper:
    description: gives you trident with mysterious powers.
    usage: /<command>
    aliases: zsn
